# Generated by Django 6.0.6 on 2026-06-11 20:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lookups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='')),
                ('table_name', models.CharField(max_length=100, unique=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'form',
            },
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Integer', 'Integer'), ('Double', 'Double'), ('Decimal', 'Decimal'), ('String', 'String'), ('Text', 'Text'), ('Date', 'Date'), ('DateTime', 'DateTime'), ('Boolean', 'Boolean'), ('Lookup', 'Lookup'), ('ForeignKey', 'ForeignKey')], max_length=20)),
                ('mandatory', models.BooleanField(default=False)),
                ('unique', models.BooleanField(default=False)),
                ('foreign_key_table', models.CharField(blank=True, default='', max_length=100)),
                ('foreign_key_field', models.CharField(blank=True, default='id', max_length=100)),
                ('default_value', models.CharField(blank=True, default='', max_length=255)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.form')),
                ('lookup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lookups.lookup')),
            ],
            options={
                'db_table': 'form_field',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('form', 'name')},
            },
        ),
    ]
