# Generated by Django 6.0.6 on 2026-06-11 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'lookup',
            },
        ),
        migrations.CreateModel(
            name='LookupValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('lookup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='lookups.lookup')),
            ],
            options={
                'db_table': 'lookup_value',
                'ordering': ['value'],
                'unique_together': {('lookup', 'value')},
            },
        ),
    ]
