# Generated by Django 6.0.6 on 2026-06-11 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('forms', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_system', models.BooleanField(default=False)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='menus', to='forms.form')),
                ('parent_menu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menus.menu')),
            ],
            options={
                'db_table': 'menu',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=False)),
                ('can_insert', models.BooleanField(default=False)),
                ('can_update', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('can_print', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='users.usergroup')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='menus.menu')),
            ],
            options={
                'db_table': 'permission',
                'unique_together': {('menu', 'group')},
            },
        ),
    ]
