# Generated by hand for dynamic reporting subsystem

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("forms", "0003_form_field_type_lookup"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150, unique=True)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "base_form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="forms.form",
                    ),
                ),
            ],
            options={"db_table": "report", "ordering": ["name", "id"]},
        ),
        migrations.CreateModel(
            name="ReportField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("display_order", models.IntegerField(default=0)),
                ("display_name", models.CharField(blank=True, default="", max_length=150)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_fields",
                        to="forms.form",
                    ),
                ),
                (
                    "form_field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="report_fields",
                        to="forms.formfield",
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "db_table": "report_field",
                "ordering": ["display_order", "id"],
                "unique_together": {("report", "form_field")},
            },
        ),
    ]

